CREATE OR REPLACE TABLE RAW_SUPPORT_TICKETS (
    TICKET_ID VARCHAR,
    SUBJECT VARCHAR,
    DESCRIPTION VARCHAR,
    CATEGORY VARCHAR,
    PRIORITY VARCHAR,
    CUSTOMER_TIER VARCHAR,
    CHANNEL VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    ESCALATED BOOLEAN
);
